# -*- coding: utf-8 -*-
"""LivrosDataFrame_FelipeYukio_N1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcOVPYmkfiXGLJf7G61c9MDArARhdvjP
"""

import this

import pandas as pd

# dados do DataFrame
dados = {
    'Titulo': ['Dom Quixote', 'Guerra e Paz', 'Moby Dick', 'Orgulho e Preconceito', '1984'],
    'Autor': ['Miguel de Cervantes', 'Liev Tolstói', 'Herman Melville', 'Jane Austen', 'George Orwell'],
    'Ano de Publicação': [1605, 1869, 1851, 1813, 1949],
    'Gênero': ['Romance', 'Histórico', 'Aventura', 'Romance', 'Distopia'],
    'Nota': ['10', '08', '07', '10', '08']
}

df = pd.DataFrame(dados)

"""# *1*. Apresente em tela (output) toda a base de dados.

Aaqui fofofofo
"""

print("DataFrame completo:")
print(df)

"""# 2. Apresente o tamanho do seu dataframe (quantas colunas x linhas)."""

print("\nTamanho do DataFrame (linhas, colunas):")
print(df.shape)

"""# 3. Acesse a linha (x) e apresente em tela todas as características do item."""

linha_indice = 0
print(f"\nCaracterísticas do item na linha {linha_indice}:")
print(df.loc[linha_indice])

"""# 4. Verifique se o dataframe está vazio."""

if df.empty:
    print("O DataFrame está vazio.")
else:
    print("O DataFrame não está vazio.")

"""# 5. Apresente em tela os 5 primeiros registros da base de dados."""

print("Os 5 primeiros registros do DataFrame:")
print(df.head(5))

"""# 6. Exclua um item (linha) de sua base de dados."""

df = df.drop(index=2)

print("\nDataFrame após a exclusão da linha com índice 2:")
print(df)

"""# 7. Adicione um item (linha) na sua base de dados."""

print("DataFrame completo antes de adicionar a nova linha:")
print(df)

novo_livro = {
    'Titulo': 'O Senhor dos Anéis',
    'Autor': 'J.R.R. Tolkien',
    'Ano de Publicação': 1954,
    'Gênero': 'Fantasia'
}

novo_livro_df = pd.DataFrame([novo_livro])

df = pd.concat([df, novo_livro_df], ignore_index=True)

print("\nDataFrame após adicionar a nova linha:")
print(df)

print("DataFrame completo antes de adicionar a nova linha:")
print(df)

df.loc[len(df)] = ['Harry Potter', 'J.K. Rowling', 1997, 'Fantasia']

print("\nDataFrame após adicionar a nova linha:")
print(df)

"""# 8. Transponha a coluna para a linha em sua base de dados."""

print("DataFrame completo antes da transposição:")
print(df)

df_transposto = df.transpose()

print("\nDataFrame após a transposição:")
print(df_transposto)

"""# 9. Apresente em tela somente a 1ª e a 2ª coluna (rótulo) da base de dados."""

colunas_selecionadas = df[['Titulo', 'Autor']]
print("1ª e 2ª coluna da base de dados:")
print(colunas_selecionadas)

duas_primeiras_colunas = df.iloc[:, :2]
print("As duas primeiras colunas da base de dados:")
print(duas_primeiras_colunas)

"""# 10. Informe como foi desenvolvido o Projeto

Primeiro abstrai da vida real um conteúdo para o meu DataFrame, depois abri o Google Colaboratory para criar o meu DataFrame usnando Python.

Utilizei algumas vezes a IA do Colab para fazer perguntas e gerar códigos para o meu DF. Utilizei o ChatGPT para formatar o link que usei para referência bibliográfica.

Um dos principais desafios durante o desenvolvimento foi descobrir qual comando eu usaria para conseguir executar determinado comando, mas usei o material disponibilizado no BlackBoard e alguns que encontrei na internet

REFERENCIAS:
Python Academy. DataFrames do Pandas. Disponível em: https://pythonacademy.com.br/blog/dataframes-do-pandas. Acesso em: [21 maio 2024].

PyData. pandas.DataFrame. Disponível em: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html. Acesso em: [21 maio 2024].
"""